image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  QT_VER: 5.10.0
  EXTRA_MODULES: .skycoder42

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: winrt_x64_msvc2017
    - PLATFORM: winrt_x86_msvc2017
    - PLATFORM: winrt_armv7_msvc2017
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015
    - PLATFORM: mingw53_32
    # only when using static tools
    - PLATFORM: static

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: winrt_x64_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_x86_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_armv7_msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017
    - PLATFORM: mingw53_32
      image: Visual Studio 2017
    - PLATFORM: static
      image: Visual Studio 2015

install:
  - git clone https://github.com/Skycoder42/QtModules.git .qtmodules-travis
  - .qtmodules-travisciwinsetup.bat

build_script:
  - .qtmodules-travisciwinbuild.bat

after_build:
  - .qtmodules-travisciwinupload-prepare.bat

artifacts:
  - path: installbuild_*_%QT_VER%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: <your encrypted token>
  artifact: /.*.zip/
  force_update: false
  on:
    appveyor_repo_tag: true

cache:
  - 'C:UsersappveyorAppDataLocalSkycoder42qpmxcache -> appveyor.yml'
